### ISSUE TITLE
Checkbox and Radio Card Component

### ISSUE THREAD

**Issue by wueestd** [swisspost/design-system#1395]
https://www.figma.com/file/xZ0IW0MJO0vnFicmrHiKaY/Components-Post?type=design&node-id=11857%3A38091&t=5mzQjs4il43FOfTt-1

**Comment by wueestd** [comment]
created first draft

**Comment by wueestd** [comment]
could you please have a look at it @rouvenpost? what do you think about the less rounded corners? :)

**Comment by wueestd** [comment]
next up: frontend review

**Comment by gfellerph** [comment]
![Image](https://github.com/swisspost/design-system/assets/1659006/b479bb43-4d7e-4ba6-80ab-7697485d0ee5)

- [ ] @wueestd, don't we want to sync focus styles with other components like the button (2px black outline 2px away from the component border)? The small grey border is not accessible.

**Comment by wueestd** [comment]
Done for the Card but not yet for the checkbox

**Comment by gfellerph** [comment]
![Image](https://github.com/swisspost/design-system/assets/1659006/7be0bf8c-aa28-4086-974c-1db3786c0106)


![Image](https://github.com/swisspost/design-system/assets/1659006/5a12c099-0eb6-47e7-9200-4e4195e30e1b)



- [ ] Focused radios and checkboxes still have a grey outline, did we not want to remove it? I don't think it's necessary.

**Comment by wueestd** [comment]
We can remove it, I thought we leave it since the molecule also has it and it is inherited from there
<img width="489" alt="image" src="https://github.com/swisspost/design-system/assets/20660048/4f76f86d-31d9-4c13-82df-acdc0ec2e150">

**Comment by wueestd** [comment]
adjusted and Atom set on Hover State
